spring:
    application:
        name: taco-cloud
    thymeleaf:
        cache: false
    datasource:
        generate-unique-name: false
        name: tacocloud
    main:
        allow-bean-definition-overriding: true
    h2:
        console:
            enabled: true
    jpa:
        properties:
            hibernate:
                "[globally_quoted_identifiers]": true
                "[globally_quoted_identifiers_skip_column_definitions]": true
logging:
    level:
        org:
            springframework:
                security: DEBUG
