spring:
    application:
        name: taco-cloud
    thymeleaf:
        cache: false
    datasource:
        generate-unique-name: false
        name: tacocloud
    data:
        mongodb:
            uri: mongodb://localhost:27017/test
